project 'Tweet-gram.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tweet-gram' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tweet-gram
  pod 'OAuthSwift', '~> 1.1.0'
  pod 'SwiftyJSON', '~> 3.1'
  pod 'Kingfisher', '~> 3.5'
  
end
